import type { Metadata } from "next"

import "./globals.css"
import Providers from "../../components/providers"
import { M_PLUS_Rounded_1c } from "next/font/google"

const mPlusRounded1c = M_PLUS_Rounded_1c({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${mPlusRounded1c.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
